version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_KEY=your_app_key
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_db_name
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=your_db_username
      - MYSQL_PASSWORD=your_db_password
      - MYSQL_ROOT_PASSWORD=root_password
